// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prontuario_do_Paciente_Online.Models;

#nullable disable

namespace Prontuario_do_Paciente_Online.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230831000451_PrimeiraMigration")]
    partial class PrimeiraMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prontuario_do_Paciente_Online.Models.Acompanhante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CidadeAcompanhante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CpfAcompanhante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnderecoAcompanhante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoAcompanhante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrauParentesco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeAcompanhante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroAcompanhante")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioAcessoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioAcessoId");

                    b.ToTable("Acompanhante");
                });

            modelBuilder.Entity("Prontuario_do_Paciente_Online.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcompanhanteId")
                        .HasColumnType("integer");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataInternacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoInternacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusPaciente")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcompanhanteId");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("Prontuario_do_Paciente_Online.Models.UsuarioAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaAcesso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoAcesso")
                        .HasColumnType("integer");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UsuarioAcesso");
                });

            modelBuilder.Entity("Prontuario_do_Paciente_Online.Models.Acompanhante", b =>
                {
                    b.HasOne("Prontuario_do_Paciente_Online.Models.UsuarioAcesso", "UsuarioAcesso")
                        .WithMany()
                        .HasForeignKey("UsuarioAcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioAcesso");
                });

            modelBuilder.Entity("Prontuario_do_Paciente_Online.Models.Paciente", b =>
                {
                    b.HasOne("Prontuario_do_Paciente_Online.Models.Acompanhante", "Acompanhante")
                        .WithMany()
                        .HasForeignKey("AcompanhanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acompanhante");
                });
#pragma warning restore 612, 618
        }
    }
}
